services:
  # ----------------------------------------------------
  # ZOOKEEPER
  # ----------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
   # healthcheck:
   #   test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
   #   interval: 10s
   #   timeout: 5s
   #   retries: 10
    healthcheck:
       test: ["CMD", "zkServer.sh", "status"]
       interval: 10s
       timeout: 5s
       retries: 10
    networks:
      - default

  # ----------------------------------------------------
  # KAFKA
  # ----------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    #depends_on:
    #  zookeeper:
    #    condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      #KAFKA_BROKER_ID: 1
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1      
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default

  # ----------------------------------------------------
  # USERSERVICE
  # ----------------------------------------------------
  userservice:
    image: userservice:latest
    container_name: userservice
    build:
      context: ./MyHomeTest/Src
      dockerfile: UserService/UserService.Api/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8000
    ports:
      - "8000:8000"
    networks:
      - default

  # ----------------------------------------------------
  # ORDERSERVICE
  # ----------------------------------------------------
  orderservice:
    image: orderservice:latest
    container_name: orderservice
    build:
      context: ./MyHomeTest/Src
      dockerfile: OrderService/OrderService.Api/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "9000:9000"
    networks:
      - default

# ----------------------------------------------------
# NETWORKS
# ----------------------------------------------------
networks:
  default:
    driver: bridge
